<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/logo.gif'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>


        <script type="text/javascript"></script>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/ingaspace.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>

        <?= $this->headLink(); ?>
    </head>
    <body>

    <?= "Test" + var_dump($this->navigation()->menu()->render()) ?>

        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="<?= $this->basePath('img/logo.gif') ?>" height="28" alt="Logo"/>&nbsp;SchumacherPhotography
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?= $this->url('/application/category') ?>">Home</a></li>
                        <li class="inactive"><a href="<?= $this->url('home') ?>">Shop</a></li>
                        <li class="inactive"><a href="<?= $this->url('home') ?>">Contact</a></li>
                        <li class="inactive"><a href="<?= $this->url('home') ?>">Get Help</a></li>
                        <li class="inactive"><a href="<?= $this->url('home') ?>">About</a></li>
                    </ul>

                </div>
            </div>
        </nav>


        <div class="container">
            <?= $this->content ?>
            <hr>   
            <footer id="footer" class="navbar navbar-fixed-bottom navbar-inverse bg-faded text-center">
                <p>&copy; <?= date('Y') ?> by <a href="mailto:Inga.Miadowicz@gmail.com">Phillip Schumacher</a> | <a href="mailto:Inga.Miadowicz@gmail.com">Inga Miadowicz</a> (technical support) | All rights reserved.
                </p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
