<?php echo $this->doctype() ?>
<html>
<head>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->headScript() ?>
</head>
<body>
    <?php echo $this->layout()->content ?>
</body>
</html>


<?php /*$this->doctype() ?>

<html lang="en" >
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Phillip Schumacher Photography')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/logo.gif'])
            //->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>


        <script type="text/javascript"></script>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/ingaspace.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>

        <?= $this->headLink(); ?>
    </head>
    <body>
    
    <!-- side menue -->
    <div id="mySidenav" class="sidenav">
      <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
      <a href="#">About</a>
      <a href="#">Contact</a>
      <a href="#">News</a>
      <a href="#">Shop</a>
    </div>

    <div id="index-sidenav-button">
        <span onclick="openNav()" class="glyphicon glyphicon-menu-hamburger"></span>
    </div>

    <!--content-->
        <div class="content2" id="content_index2">
            <?= $this->content2 ?>
        </div>

        <?= $this->inlineScript() ?>
    </body>
</html>
