
<?php

  /**
   author: Inga Miadowicz
   date: 22.11.2016
   description: displays an album. This sonsist out of a panel with a colored title,   image and a description in bootstrap style. By rendering this view as partial you can add severel albums to a page.
   
  */

?>

    <div class="col-sm-4" >
      <div class="panel panel-primary">
        <div class="panel-heading">Title Album 2</div>
        <div class="panel-body"><img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image"></div>
        <div class="panel-footer">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam</div>
      </div>
    </div>

  