<?php
	//echo $this->link_photography;
	$link_fineart = "";
	$link_bts = "";

	//echo url("/photography",null,null,null,);

?>

<div id="startpage_layout_tree" class="startpage_layout_full_picture_background row">
	<div id="index_container_title_menue" class="Jumbotron center text-center col-sm-12 col-xs-12 col-md-12 col-lg-12">
		<div class="index_title">
			<h1>Phillip Schumacher</h1>
		</diV>
		<div class="index_menue_subtitle">
			<p> 
			<?
				/*
					To-Do: url as variable 
					controller -> click?
				*/
			?>
				<a href='http://ingaspace.marcodoerfler.de/public/category/photography'>Photography</a> / 
				<a href="http://ingaspace.marcodoerfler.de/public/category/fineart">Fine Art</a> / 
				<a href="http://ingaspace.marcodoerfler.de/public/category/illustrations">Illustrations</a>

				<?= $APPLICATION_PATH ?>
			</p>
		</div>
	</div>
</div>

